#!/usr/bin/env python3
"""Create a local ReverseLab task skeleton for a board and task name."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BOARDS = {"ctf-website", "android", "windows", "general", "misc"}


def slugify(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip(".-_").lower()
    return slug or "task"


def board_note_template(board: str) -> Path:
    mapping = {
        "ctf-website": ROOT / "templates" / "notes" / "ctf-website-writeup.md",
        "android": ROOT / "templates" / "notes" / "android-apk-analysis.md",
        "windows": ROOT / "templates" / "notes" / "windows-pe-analysis.md",
        "general": ROOT / "templates" / "notes" / "sample-analysis.md",
        "misc": ROOT / "templates" / "notes" / "sample-analysis.md",
    }
    return mapping[board]


def manifest_for(board: str, name: str, slug: str) -> dict:
    return {
        "schema": 1,
        "name": name,
        "slug": slug,
        "board": board,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "evidence": [],
        "dead_ends": [],
        "next_actions": [
            f"Read AI-USAGE.md and boards/{board}/AI-USAGE.md",
            "Run kb_router for any concrete signal before tool execution",
            "Write findings to notes/ and raw evidence to exports/",
        ],
        "autopilot": {
            "last_round_id": "",
            "rounds": [],
        },
    }


def create_task(board: str, name: str, overwrite: bool = False) -> dict:
    if board not in BOARDS:
        raise ValueError(f"unknown board: {board}. Choose one of: {', '.join(sorted(BOARDS))}")
    slug = slugify(name)
    case_dir = ROOT / "cases" / slug
    exports_dir = ROOT / "exports" / board / slug
    notes_dir = ROOT / "notes" / board
    reports_dir = ROOT / "reports" / board / slug
    manifest_path = case_dir / "ai_manifest.json"
    note_path = notes_dir / f"{slug}.md"
    report_readme = reports_dir / "README.md"

    created: list[str] = []
    for directory in (case_dir, exports_dir, notes_dir, reports_dir):
        directory.mkdir(parents=True, exist_ok=True)
        created.append(str(directory.relative_to(ROOT)))

    if manifest_path.exists() and not overwrite:
        raise FileExistsError(f"manifest already exists: {manifest_path.relative_to(ROOT)}")
    manifest_path.write_text(
        json.dumps(manifest_for(board, name, slug), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    template = board_note_template(board)
    note_text = template.read_text(encoding="utf-8", errors="replace") if template.exists() else f"# {name}\n"
    if note_path.exists() and not overwrite:
        raise FileExistsError(f"note already exists: {note_path.relative_to(ROOT)}")
    note_path.write_text(
        f"<!-- Local task note generated by scripts/misc/new_task.py -->\n\n"
        f"# {name}\n\n"
        f"- Board: `{board}`\n"
        f"- Case: `cases/{slug}/ai_manifest.json`\n"
        f"- Exports: `exports/{board}/{slug}/`\n"
        f"- Reports: `reports/{board}/{slug}/`\n\n"
        f"---\n\n{note_text}\n",
        encoding="utf-8",
    )

    if not report_readme.exists() or overwrite:
        report_readme.write_text(
            f"# Report Workspace: {name}\n\n"
            f"- Board: `{board}`\n"
            f"- Case manifest: `cases/{slug}/ai_manifest.json`\n"
            f"- Note: `notes/{board}/{slug}.md`\n\n"
            "Final reports generated here are local evidence and are ignored by Git.\n",
            encoding="utf-8",
        )

    return {
        "name": name,
        "slug": slug,
        "board": board,
        "manifest": str(manifest_path.relative_to(ROOT)),
        "note": str(note_path.relative_to(ROOT)),
        "exports": str(exports_dir.relative_to(ROOT)),
        "reports": str(reports_dir.relative_to(ROOT)),
        "created_dirs": created,
        "git_note": "Generated task evidence is local by default and should not be committed.",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--board", required=True, choices=sorted(BOARDS))
    parser.add_argument("--name", required=True)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    try:
        payload = create_task(args.board, args.name, args.overwrite)
    except Exception as exc:
        print(json.dumps({"overall": "FAIL", "error": str(exc)}, ensure_ascii=False, indent=2))
        return 1
    print(json.dumps({"overall": "PASS", **payload}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

